### ISSUE TITLE
Broken app-layout

### ISSUE THREAD

**Issue by DinuMihnea** [appreciated/vaadin-app-layout#106]
Duplicate of #102
Hi.
I have same issue in my project.
The first display of app is broken, after refresh the page, app starts work.
I tried to find this bug in [vaadin-app-layout-demo](https://app-layout-wrapper.herokuapp.com/) and sometimes is present (see attachment)
![demo-error](https://user-images.githubusercontent.com/20513656/37394442-716716ba-277c-11e8-8bda-bad654e0a94b.png)
Please help to find a solution
Thanks

**Comment by appreciated** [comment]
Hi Dinu! 
Do you know any way to reproduce it consistently?

**Comment by DinuMihnea** [comment]
Now I search.... until without results
I'll let you know when I find a way.

**Comment by DinuMihnea** [comment]
During the tests I found strange warning:
_[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths._
Maybe this is cause of the problem?

**Comment by DinuMihnea** [comment]
For reproduce the bug (in Chrome) you need to clear and disable browser cache and do a several refreshes.

**Comment by appreciated** [comment]
First of all thank you Dinu for your investigation! I think the approach @deyaeddin choose to build the dependencies caused this error to disappear it hat something to do with the es5-adapter, but since vaadin elements allows to approach this differently this issue now seems to be sorted out.  I will need some more time to test this. And will hopefully release an update this week.

**Comment by DinuMihnea** [comment]
Thanks for good news. I'm in waiting for the new version.
Thanks for all!

**Comment by appreciated** [comment]
Sorry for the additional delay. I couldn't reproduce the issue anymore.
