### ISSUE TITLE
Indicating which submenu item has been opened

### ISSUE THREAD

**Issue by mirkoliver** [appreciated/vaadin-app-layout#107]
I have a question regarding behaviour variant "TOP":

When you select a menu item in a submenu , the view is displayed, the submenu closes and it isn't visible anymore, which view has been opened. There is neither a line under the submenu title nor it is indicated which view has been opened.

Therefore I would like to program a workaround: add the opened view title to the submenu title.

For example:
- Submenu = "Master data"
- Menu Item 1 = "Person"
- When menu Item 1 is opened, the title of the submenu changes to "Master data > Person".
- At best the submenu title is underlined.

Is there a chance to accomplish this?

**Comment by appreciated** [comment]
Sure since it is allowed to replace any of the MenuElements components you can replace the provider by using

```
 AppLayoutComponent drawer = AppLayout.getDefaultBuilder(variant)
                .withTitle("App Layout")
                ...
                .withSubmenuElementProvider(new CustomTopSubmenuNavigationElementFactory())
                .build();
```

To see how to implement your own Factory checkout the default implementation [DefaultTopSubmenuNavigationElementFactory](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/builder/factories/top/DefaultTopSubmenuNavigationElementFactory.java).

**Comment by mirkoliver** [comment]
Thank you for your quick answer!

I've put a breakpoint to `DefaultTopSubmenuNavigationElementFactory.get(SubmenuNavigationElement element)` and it has only been called once - when the menu is constructed. But not when views are selected from submenus. How can this solve my problem to change the submenu title when menu items are selected?

**Comment by appreciated** [comment]
> Thank you for your quick answer!

You are welcome! 

> I've put a breakpoint to  DefaultTopSubmenuNavigationElementFactory.get(SubmenuNavigationElement element) and it has only been called once - when the menu is constructed. But not when views are selected from submenus. How can this solve my problem to change the submenu title when menu items are selected?

This is probably because you have only one `SubmenuElement` in your `AppLayoutComponent`. So the Factory will only produce one Component. The Key in your case is not the Factory but the _Component_ you produce with it you will need to manipulate the Component, f.e. add a `OnClickListener`. 

> P.S.: I've used an older version (0.9.17) where DefaultTopSubmenuNavigationElementFactory still has been DefaultTopSubmenuNavigationElementProvider.
That shouldn't be a problem just checkout the "provider" then.
