### ISSUE TITLE
Bundle polymer web components

### ISSUE THREAD

**Issue by sergei-iliev** [appreciated/vaadin-app-layout#112]
Hi,
Is it possible to bundle all web components to avoid multiple server hits at initial app layout load?

Regards

**Comment by deyaeddin** [comment]
Hi @sergei-iliev 
Thanks for the suggestion, but opt out to bundle deliberately on this add-on because as polymer documentation: 

> bundled or unbundled resources depends on the behaviour and capabilities of both server and browser.  

refer to [To bundle or not to bundle?](https://www.polymer-project.org/2.0/toolbox/build-for-production) from Polymer site.

However, YES ... you can bundle all your web components on the application level. If you modify the polymer.json to  bundle: true with your build, the Application will run normally.
