### ISSUE TITLE
How to add components, that only display 

### ISSUE THREAD

**Issue by mirkoliver** [appreciated/vaadin-app-layout#123]
How can I add simple components, that are not menu items and only display something - for example the actual date?

In the following example I'd like to add a Label to the footer just above the "Sign Out"-clickable.

I've tried this with `add(new Label("TEST"), Section.FOOTER) `- nothing happens.
And with `addToAppBar(new Label("TEST"))` it appears under the clickable.

```
AppLayoutComponent drawer =
    AppLayout.getCDIBuilder(variant)
        .withViewProvider(() -> viewProvider)
        .withNavigationElementInfoProvider(new DefaultNavigationElementInfoProducer())
        .withDesign(AppLayoutDesign.MATERIAL)
        .add(MyView.class)
        .addClickable("Sign out", VaadinIcons.SIGN_OUT, e -> logout(), Section.FOOTER)
        .build();
```

**Comment by appreciated** [comment]
Seems like a bug to me 😐

**Comment by mirkoliver** [comment]
I'm using `setDrawerVariant(Behaviour.TOP)`

**Comment by mirkoliver** [comment]
So in that behaviour it's not "under" or "above" but "right" and "left" ;)

**Comment by appreciated** [comment]
Yeah that might be the cause for the problem. 
You see when adding a component to "the" TOP menu the are actually two menus one a the top and one at the left, which will only be shown if you have a small screen. Problem is I cannot display the same component twice as this would raise an exception at runtime. 
The API currently does not differentiate between these two menu entries the component will only be added to one of the both menus.

But there is a solutions to the problem, since you can access the component directly, you can simply add two component to it. I will give you an example later.

> So in that behaviour it's not "under" or "above" but "right" and "left" ;)
This is due to convenience reasons not optimal I know. I should probably use two different builders instead for these behaviours to make things more clear for the user.

**Comment by appreciated** [comment]
Sorry for taking so long to answer this you can do it as follows:
```
AppLayoutComponent appLayout = AppLayout.getDefaultBuilder(Behaviour.TOP)
        ...
        .build();

appLayout.addToDrawerHeader(new Button("Test"));
appLayout.addToDrawer(new Button("Test"));
appLayout.addToDrawerFooter(new Button("Test"));
appLayout.addToTopHeader(new Button("Test")); // Will fail on none TOP Behaviours appLayout.addToTop(new Button("Test")); // Will fail on none TOP Behaviours 
appLayout.addToTopFooter(new Button("Test")); // Will fail on none TOP Behaviours 
```
