### ISSUE TITLE
Programaticaly closing side menu do not work properly

### ISSUE THREAD

**Issue by bekirmavus** [appreciated/vaadin-app-layout#127]
i try to close side menu programaticaly but it doesn't work properly.

versiyon 1.0.0
Vaadin 8.4.3
Behaviour.LEFT_RESPONSIVE

https://github.com/appreciated/vaadin-app-layout/blob/dev-8.x/app-layout-addon/src/main/java/com/github/appreciated/app/layout/behaviour/AppLayoutComponent.java#L17-L31
![bug](https://user-images.githubusercontent.com/6548558/42015707-14ff2ef2-7ab1-11e8-9618-0f7273ebb1c2.gif)

**Comment by appreciated** [comment]
Can you please describe what isn't working? Since the Gif actually shows that it does work.

**Comment by bekirmavus** [comment]
at console, i execute js command that you use at here:

https://github.com/appreciated/vaadin-app-layout/blob/dev-8.x/app-layout-addon/src/main/java/com/github/appreciated/app/layout/behaviour/AppLayoutComponent.java#L17-L31

side menu closes but view not resize. at first gif it is not clear because of colors. Here is a another gif:

![bug4](https://user-images.githubusercontent.com/6548558/42028730-c6223020-7ad5-11e8-8aa4-65aa7b6cd882.gif)

**Comment by appreciated** [comment]
This is just a misunderstanding of the "close" function. 
First off, I am not giving support for the close function (usage is at your own risk). But I must admit that this currently not mentioned in the documentation. So if you use it you need to know what you are doing. 
Now a little more detailed the problem is that the `app-layout` Webcomponent allows you to close the menu even if the drawer is [`persistent`](https://www.webcomponents.org/element/PolymerElements/app-layout/elements/app-drawer#property-persistent), which is the case when using the LEFT_RESPONSIVE behaviour.
This is f.e. why there is a `closeDrawerIfNotPersistent` function, which shouldn't do anything in this case.

The reason why the content doesn't move along is that the css isn't optimized for the state you are producing with the `close` function.

**Comment by bekirmavus** [comment]
ok. do you have a api that i can make custom menu button. may be i can handle my problem by it.

**Comment by appreciated** [comment]
You can either use a behavior that is non persistent (Left and Left_Overlay). Or you could make a pull request and optimize the CSS for your specific use case.

**Comment by zaheer1389** [comment]
> ok. do you have a api that i can make custom menu button. may be i can handle my problem by it.

have you found the solution to the above issue? I have the same issue. If you have achieved the same then can you please tell me how to get the same.

**Comment by appreciated** [comment]
@zaheer1389 Consider to open a new issue, not sure if you have the same use case or version (this issue is about the Vaadin 8 version)
