### ISSUE TITLE
Add methods to add menu elements 

### ISSUE THREAD

**Issue by arivanajoki** [appreciated/vaadin-app-layout#141]
In addition to AbstractViewAppLayoutBuilder's methods like:

**public T add(String caption, Resource icon, DefaultBadgeHolder badgeHolder, View element)**

it would be nice to have similar methods in AppLayoutComponent class like

**public NavigatorNavigationElement addNavigationElement(String caption, Resource icon, DefaultBadgeHolder badgeHolder, View element)**

Those methods will be useful if structure of navigation elements is depending on some conditions and during runtime there is need to leave some items out from the navigation structure.

**Comment by appreciated** [comment]
I guess you want to have this feature in the Vaadin 8 version? 
The method you proposed:
```
public NavigatorNavigationElement addNavigationElement(String caption, Resource icon, DefaultBadgeHolder badgeHolder, View element)
``` 
Won't be able to archive the results you want to have. 
> Those methods will be useful if structure of navigation elements is depending on some conditions and during runtime there is need to leave some items out from the navigation structure.

The reason for this is that a `NavigatorNavigationElement` Is not a component, but more a "Component Factory". This has some architectural reasons and was found to be a bad decision. Also this is already removed in the Vaadin Flow Version. 

Backporting these changes to the Vaadin 8 Version would be a lot of work since there were some tremendous changed made to the Navigator (-> Router). But it wouldn't be impossible. 

I instead suggest that you rebuild the whole menu if you need to show different menu entries on different occasions. Not the best workaround I know but I'm currently not having the time and neither the motivation to put in the hours for this change.

**Comment by appreciated** [comment]
Feel free to reopen if you plan on backporting the changes to V1.*
