### ISSUE TITLE
Add ClickListener to SubMenuButton?

### ISSUE THREAD

**Issue by matheso** [appreciated/vaadin-app-layout#183]
I understand we can add SubMenu Items like so:

```
.add(SubmenuBuilder.get("SUB_MENU_PARENT", VaadinIcons.PLUS)
                        .add("SUB_MENU_ITEM", VaadinIcons.STAR, new View2())
                        .build() )   
```          
and clickable menu items like so:

`.addClickable("SUB_MENU_PARENT", VaadinIcons.PLUS, clickEvent -> { });`

but how do I make the "SUB_MENU_PARENT" menu element clickable so that it

**1.** Adds / Navigates to a View 
**2.** Still expands the sub-menu when clicked

Right now, it doesn't do #1. Only menu-items, sub-menu items, and clickables can add a view. How do Sub Menu Headers add views too?

Thanks!

**Comment by appreciated** [comment]
@matheso Currently it isn't possible to archive your requirements:
> 1. Adds / Navigates to a View
> 2. Still expands the sub-menu when clicked

 by using the current `SubmenuBuilder` API. 
I hope you understand that we cannot implement any feature just because a single user needs it. But since this is open source you are welcome to dig yourself into the code and add this feature by creating a pull request. This may sound a bit dissuasive but the related classes aren't actually that complicated. 
If you need further assistance, you are welcome to join me on Slack or post some questions here.

The related classes are the following:
- [`LeftSubMenuBuilder`](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/component/appmenu/left/builder/LeftSubMenuBuilder.java)
- [`LeftSubmenuComponent`](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/component/appmenu/left/LeftSubmenuComponent.java)

Your Usecase would require to add an additional method + constructor to the `LeftSubMenuBuilder`:
```
public static LeftSubMenuBuilder get(String title, Icon icon, Component view) {
     return new LeftSubMenuBuilder(title, icon, view);
}

public static LeftSubMenuBuilder get(String title, Icon icon, Class<? extends Component> className) {
     return new LeftSubMenuBuilder(title, icon, className);
}
```
Also an additional Constructor in the `LeftSubmenuComponent` which you can copy partly from [`LeftNavigationComponent`](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/component/appmenu/left/LeftNavigationComponent.java)

**Comment by appreciated** [comment]
Closed due to inactivity
