### ISSUE TITLE
AppLayout to extend Vaadin.ThemableMixin for better theming options

### ISSUE THREAD

**Issue by tamasmucs** [appreciated/vaadin-app-layout#189]
As we know, at this point it is not possible to style DOM elements that are in shadow via plain css.  Unfortunately there is no standard workaround for this issue either. However, the Vaadin theme does have their own solution by "exposing" certain parts or states of their webcomponents in forms of dom parts. That way, users of components that extend Vaadin.ThemeableMixin can inject their own styles into the webcomponent that are open for styling. 

https://github.com/vaadin/vaadin-themable-mixin

To achieve this, we need to do some modifications and extend Vaadin.ThemeableMixin. For example, a vaadin-button class has the following signature:
``
class ButtonElement extends
        Vaadin.ElementMixin(
          Vaadin.ControlStateMixin(
            Vaadin.ThemableMixin(
              Polymer.GestureEventListeners(Polymer.Element)))) { 
``

**Comment by appreciated** [comment]
So before get really going with this issue, there needs to be specified which `part` should be stylable, since those need to have their `part` attribute set with a specific value. And also how should these be styled. 

I think that it doesn't make sense to make every single element in every Behaviour accessible. 

A List which elements are used. 
- `<app-toolbar>`
- `<app-drawer>`
- `<app-header-layout>`
- `<paper-icon-button>` (the toggle for the menu)
- `<app-drawer-layout>`

Problem with these elements is that these do not always have the same function, which is due to the differences in function in the [Behaviours](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/behaviour/Behaviour.java) available. So styling these elements might be confusing for the user. Maybe there should some naming introduced which us understandable for the users but can point to different elements in the different behaviours.

**Comment by appreciated** [comment]
Postponed to 2.02 since this issue was not ready for implementation on release.

**Comment by appreciated** [comment]
@tamasmucs Anything to add?

**Comment by appreciated** [comment]
closed by #224
