### ISSUE TITLE
Polymer custom-style.html 404

### ISSUE THREAD

**Issue by cedricaebi** [appreciated/vaadin-app-layout#259]
**Describe the bug**
"GET http://localhost:8080/bower_components/polymer/lib/elements/custom-style.html net::ERR_ABORTED 404" which probably comes from a shared style of yours.

I get this error only with 3.0.0.beta1. With both Lumo and Material. 

** Additional Information (please complete the following information):**
 - Browser all of them
 - Version 3.1.0.beta1

**Comment by Springrbua** [comment]
I noticed the same bug when trying to switch to the 3.0.0.beta1.
I tryed to locate the wrong import and found only [app-layout-styles](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/resources/META-INF/resources/frontend/src/com/github/appreciated/app-layout/app-layout-styles.html) with a probably wrong import. There is one `../` too much.
However, to my understanding, this file shouldn't be needed, since there are the 2 theme-specifc files for [Lumo](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/resources/META-INF/resources/frontend/theme/lumo/com/github/appreciated/app-layout/app-layout-styles.html) and [Material](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/resources/META-INF/resources/frontend/theme/material/com/github/appreciated/app-layout/app-layout-styles.html), which seem to have the correct imports.

**Comment by appreciated** [comment]
> Version 3.1.0.beta1
You mean 3.0.0.beta1 right?

**Comment by Springrbua** [comment]
> I get this error only with **3.0.0.beta1**. With both Lumo and Material.
>...
> Version 3.1.0.beta1

I am pretty sure this was only a typo.

**Comment by cedricaebi** [comment]
Jup sorry my bad.. of course 3.0.0.beta1

**Comment by phobiac** [comment]
> This is not a too problematic issue. This should not cause any problem with the application itself. Will fix in `beta2`.

I'm not sure what your timeline is for 3.0.0.beta2, but this is causing an application breaking bug on my end. I've had to bump back down to 2.1.0.beta1 to not experience it as 2.1.0 is not compatible with Vaadin 13+.

I have a login page (using the vaadin-login-flow addon) that after authentication is supposed to send users to the default route. When I build with 3.0.0.beta1, after login the app tries to route to this custom-style.html page for some reason.
```
Could not navigate to 'bower_components/polymer/lib/elements/custom-style.html'
Reason: Couldn't find route for 'bower_components/polymer/lib/elements/custom-style.html'
```

I'm willing to share more about my setup if that would help solve this.

**Comment by Springrbua** [comment]
@appreciated I noticed, that in our application there is no space between the title in the app-bar and the left border since version 3.0.0.beta1 and I guess, it has to do with this bug.
Also, I am not sure if this bug is really related to the `app-layout-styles`, since they should never be loaded on the client and therefore the (wrong) import of `custom-styles` should not be triggered.
So either this bug is related to some other file or the `app-layout-styles` is falsely loaded on the client.

**Comment by appreciated** [comment]
> I'm willing to share more about my setup if that would help solve this. 

No need this issue can be fixed very easily. 

> after login the app tries to route to this custom-style.html page for some reason.

This sounds really wierd.

**Comment by appreciated** [comment]
> I noticed, that in our application there is no space between the title in the app-bar and the left border since version 3.0.0.beta1 and I guess, it has to do with this bug.

@Springrbua This is probably related to introduction of #190. I needed to replace the `HorizontalLayout` with `FlexLayout` to support changing the `flex-direction` please open another issue for this. `FlexLayout` does not have a `setSpacing()` method.

**Comment by appreciated** [comment]
@phobiac [checkout 3.0.0.beta2](https://vaadin.com/directory/component/app-layout-add-on/3.0.0.beta2)

**Comment by phobiac** [comment]
@appreciated That fixed it for me! Thank you.
