### ISSUE TITLE
Slider bar without the AppBar

### ISSUE THREAD

**Issue by borax1974** [appreciated/vaadin-app-layout#5]
Great addon, thanks for the effort. 
Is it possible to use only the slider bar(drawer) without the app bar?

**Comment by appreciated** [comment]
Hallo Borax I don't know how much of the API you already have discovered and if you found the following method.

````
public class DemoUI extends UI {
  ...
  protected void init(VaadinRequest request) {
    setContent(NavigationDrawerBuilder.get()
    .withVariant( ... )
    .build());
  }
}
````
And if one of the offered Variants satisfy you. 

I do not recommend removing the app bar from because from a UX point of view, about no user will find the drawer if you remove the AppBar. 

But If you really want no app bar yes it is possible to do so: 
1. You could either use the variant LEFT or LEFT_OVERLAY and hide the AppBar by setting some css variables and applying some scss: 

$app-bar-height: 0px;
$app-bar-shadow: none;

app-toolbar {
    display: none;
}

2. (This requires more work but is a cleaner solution) Or create your own Custom Layout and use your own template. 

Checkout the package com.github.appreciated.app.layout.drawer, the associated Resource folder and <project-folder>/webapp/VAADIN/addons/app-layout figure out how I made polymer app-layout working and try to mimic it and make only [app-drawer](https://www.webcomponents.org/element/PolymerElements/app-layout/elements/app-drawer) work. It is actually not that complicated than it may sounds. The Examples are very straight forward.

**Comment by borax1974** [comment]
Thanks, I'll look into it. You are correct about the appbar, but my problem is that I already have one in my project :) I just need a drawer that will play nice with my appbar.

**Comment by appreciated** [comment]
@borax1974 Ah yeah you are right didn't think about that usecase 🙂 you then might also want to checkout   
> AbstractNavigationDrawer::toggleDrawer()
