### ISSUE TITLE
Grid on content view does not expand on menu collapsing

### ISSUE THREAD

**Issue by mscho88** [appreciated/vaadin-app-layout#58]
I placed a grid with setSizeFull on the content view. (e.g. LEFT_RESPONSIVE)

But it does not expand to fit the content on the right side after the left menu collapses.

**Comment by appreciated** [comment]
This from my current knowledge due to the usage of CustomLayout (The AppLayout is wrapped inside a CustomLayout), the Vaadin grid does not get notified when the layout was resized. 

This is definitly a bug of this layout that I currently don't know how to fix. There are some workarrounds though. f.e. [you can force the grid to redraw itself](https://stackoverflow.com/questions/31861375/vaadin-refresh-grid-after-row-modification) but I know this is not a solution.

**Comment by appreciated** [comment]
This works pretty good for me:
```
@import "../valo/valo.scss";

@mixin mytheme {
  @include valo;
  .v-grid-scroller-horizontal {
    width: 100% !important;
  }
  .v-grid-tablewrapper {
    width: 100% !important;
  }
}
```

**Comment by mscho88** [comment]
Thank you 
It works perfect !
