### ISSUE TITLE
Indent submenu elements

### ISSUE THREAD

**Issue by kamuffe** [appreciated/vaadin-app-layout#67]
Hi.

It would be nice if submenu elements are indented a little bit. This would give a better overview about what is a topmenu element and what is a submenu element.

The different color is good, but not sufficient.

Maybe you could provide a css variable as well as the colors, so that everyone could adjust the depth of the indention separately.

Thank you very much.

**Comment by appreciated** [comment]
> It would be nice if submenu elements are indented a little bit. This would give a better overview about > what is a topmenu element and what is a submenu element.
> 
> The different color is good, but not sufficient.

I guess this depends very much on personal preference, design guidelines and the usecase. 

The material guidelines are quite specific here, for a very deep nesting they don't encourage to use indention. For menus with a very flat tree it doesn't encourage to use collapsing menus but therefore indention. 

It is quite easy to get the effect you want since you only need to add some padding:
```
.app-layout-submenu-container {
    padding-left: 30px;
}
```

> Maybe you could provide a css variable as well as the colors, so that everyone could adjust the depth of > the indention separately.

I guess I can do that. But I haven't ever heard of a css variable 😛. But maybe you mean a sass or a scss variables 🙂.

**Comment by luisrafaelinf** [comment]
> I guess I can do that.

Remember when the menu is small 

this

```
.app-layout-submenu-container {
    padding-left: 30px;
}
```

change to 

```
.app-layout-submenu-container {
    padding-left: 0px;
}
```


I suppose.

**Comment by appreciated** [comment]
@luisrafaelinf thanks for the hint I took that in account by adding two variables to set the indention for "small" menus and the expanded menus separably.

**Comment by appreciated** [comment]
Since I will need more time to add the documentation / JavaDocs I added an additional release before 1.0.0 to roll out the new features to you.
