### ISSUE TITLE
Backward Compatibility broken

### ISSUE THREAD

**Issue by frangelh** [appreciated/vaadin-app-layout#76]
Hey there, I just noticed that few updates ago you started using 
**componet.addStyleNames(...)** 
should use the uggly .addStyleName() N-times instead 
And this broke with the backward compatibility on the same vaadin 8.x

**Comment by appreciated** [comment]
Since version 0.9.4 this Addon requires Vaadin 8.1+. This is also mentioned on the bottom right side in the Vaadin directory. But I guess I should also upgrade the Readme. 

True it broke backward compability but I actually see no point in replacing the `Component::addStyleNames(...)` with `Component::addStyleName(...)` just to support Versions prior `8.1.rc1`. 
Using Vaadin 8.0 over Vaadin 8.1+ has no advantages and upgrading is possible with very little work (changing a number in the POM). 
So from a user point of view the only _bad thing_ is that if you choose to upgrade the version of this addon you will have to upgrade your Vaadin version, which I think isn't too bad _as long it doesn't come with any other work_.

Note: I won't do this for major releases (Vaadin 8 -> Vaadin 10).
