### ISSUE TITLE
Spring Boot Annotation @MenuIcon accepting more than VaadinIcon

### ISSUE THREAD

**Issue by dangllucas** [appreciated/vaadin-app-layout#81]
Feature for AppLayoutAddon.

Following [JLS](https://docs.oracle.com/javase/specs/#9.7) it is not allowed to use Interfaces as Annotation values.

The Problem is, I have my custom Font Icons and cant use them with the Layout now, because it only accepts VaadinIcons in @MenuIcon.

Do you have any clue how to implement this?
Just give me an idea, and ill do it myself, but I dont have an Idea right now -sadly-

**Comment by appreciated** [comment]
"Simply" provide your Custom Implementation of `NavigationElementInfoProvider` and set it via.
Assuming you are using Spring [copy the Code from the default Implementation](https://github.com/appreciated/vaadin-app-layout/blob/master/app-layout-addon/src/main/java/com/github/appreciated/app/layout/builder/providers/DefaultSpringNavigationElementInfoProvider.java) And fit it to your needs.

**Comment by dangllucas** [comment]
I asked to fast, just found it myself, but thx for your help aswell.

Maybe this would be a good idea for a more general implementation. (Maybe work with Reflection here)

**Comment by appreciated** [comment]
The problem here is that pending on the CDI Framework the user wants the View Annotation is differently which means that there is no general solution to this. 
What can be done is to improve some abstraction to make it easier for the user of a specific framework. The amount of saved lines depends heavily on the use case. 
Making things easier for the user is always a good thing but, as a developer I always have to check if it is actually worth it and how many users would actually be affected by this new feature? 
My personal opinion is this are currently +/- 5 users which actually would be affected which is too less to prioritize it currently since I'm lacking of time until this beginning of January.  
If you are interested in developing this feature/enhancement you may make a pull request. 
I gladly review and accept the changes, currently I have no time to develop it personally.

**Comment by appreciated** [comment]
What you can do now: 
```
setContent(AppLayout.getCDIBuilder(Behaviour.LEFT_RESPONSIVE_HYBRID)
        ...
        .withNavigationElementInfoProvider(
                new DefaultSpringNavigationElementInfoProvider()
                        .withIconProvider(info -> info.getAnnotation(MenuIcon.class).value())
        )
        ...
        .build());
```
