### ISSUE TITLE
Update label of drawer button

### ISSUE THREAD

**Issue by RadoJoker** [appreciated/vaadin-app-layout#84]
I am using a drawer and I need to change the text of the clickable button from "Connect" to "Disconnect" and viceversa depending on a boolean, how can I do it? Here the piece of code: 
```
AppLayout drawer = AppLayoutBuilder.get(variant).withTitle("App Layout")
   .addClickable("Connect", VaadinIcons.EXCHANGE, new ClickListener() {
      @Override
      public void buttonClick(ClickEvent event) {
         //change the text from "Connect" to "Disconnect"
      })
```
Best regards
Radostin

**Comment by appreciated** [comment]
Hello Radostin!

This is can be archived in different ways since the `Button` is a component and it is possible to straight add components to the menu, you can do as follows:
```
NavigationButton button = new NavigationButton("title", VaadinIcons.QUESTION);
button.addClickListener(clickEvent -> button.setCaption("..."));

AppLayout drawer = AppLayoutBuilder.get(variant)
    ...    
    .add(button)
    ...            
    .build();
```
Also since the title + label part of the `NavigationButton` is a simple Vaadin Button you can do this even more compact by using the the `Button` Component passed within the event:
```
AppLayout drawer = AppLayoutBuilder.get(variant)
    ...    
    .addClickable("title", VaadinIcons.QUESTION, clickEvent -> 
        clickEvent.getButton().setCaption("...")
    )
    ...            
    .build();
```

Let me know if that helped 🙂

**Comment by RadoJoker** [comment]
Worked like a charm! Thank you!
