### ISSUE TITLE
Separate View name from label.

### ISSUE THREAD

**Issue by bsutton** [appreciated/vaadin-app-layout#90]
I have a UI for controlling an irrigation system.

The UI allows a user to configure 'garden beds' as well as to control 'garden beds'.
There is a separate view for each of these.

The 'configuration' view appears under a sub menu 'configuration'.

I want both of these views to have the same label in the menu but I need to be able to navigate to them separately.
e.g.
```
UI.getCurrent().getNavigator().navigateTo(GardenBedEditorView.NAME);
```

Currently the AppLayout method uses the 'caption' for both the view name and the menu label.
We need another method signature that allows these to be defined separately.

e.g.

```
	AppLayout layout = AppLayoutBuilder.get(Behaviour.LEFT_RESPONSIVE)
				.withTitle("Pi-gation")
				.withDefaultNavigationView(gardenBedView)
				.withDesign(AppBarDesign.MATERIAL)
				.add(GardenBedView.LABEL, GardenBedView.NAME, VaadinIcons.CLOUD, gardenBedView)
                                .build();
```
The method signature would therefore be:

```
  public AppLayoutBuilder add(String caption, String viewName, Resource icon, View element) {
        return add(caption, icon, null, element, Position.DEFAULT);
```

**Comment by appreciated** [comment]
>   `AppLayoutBuilder add(String caption, String viewName, Resource icon, View element)`
There actually already is this method though the signature is slightly different. Which allows you exactly what you aim to archive. 

`AppLayoutBuilder add(String caption, String path, Resource icon, Class<? extends View> element, Position position) `

What in fact is bad (and unwanted) that the Signature with `View` instead of  `Class<? extends View>` is missing, for now I recommend, to use this one:
`add(String caption, String path, Resource icon, DefaultBadgeHolder badgeHolder, View element, Position position)` 
Since DefaultBadgeHolder is nullsafe simply pass `null`.

**Comment by bsutton** [comment]
It's not clear what I should pass for the path.

**Comment by appreciated** [comment]
> It's not clear what I should pass for the path.
Which is why I wrote 
> (path == viewName)

And also provided a code example
> (f.e. add("caption", "viewname", <icon>, null, view, Position.DEFAULT) ).

The (URL-)`Path` is supposed to be the same as `viewname` it's just a matter of perspective I guess. 

Since Vaadin 8.2 there is the Annotation `@PushStateNavigation` which you can add to your UI class. Which will make the viewname to become part of the URL path (when being navigated to).
